// Generated by bin/compose-frontend.sh — the client entry of every plugin frontend this site uses.
// The bare template has none; a composed template imports "./<plugin-id>/index" per plugin.
export {};
