// Generated by bin/compose-frontend.sh — build-time hooks of the plugin frontends this site uses.
// The bare template has none.
import type { LayoutData, SiteIdentity } from "../lib/layout";

export interface PluginHeadContext {
	layout: LayoutData;
	site: SiteIdentity;
	url: URL;
}
export interface PluginServer {
	id: string;
	/** HTML appended to <head> on every page. */
	head?: (ctx: PluginHeadContext) => Promise<string> | string;
	/** Fill this plugin's content markers (e.g. Commerce's data-product-grid) in page-builder HTML. */
	fillSlots?: (html: string) => Promise<string>;
}

export const plugins: PluginServer[] = [];

export async function pluginHead(ctx: PluginHeadContext): Promise<string> {
	const parts: string[] = [];
	for (const p of plugins) if (p.head) parts.push(await p.head(ctx));
	return parts.join("\n");
}

export async function fillPluginSlots(html: string): Promise<string> {
	let out = html;
	for (const p of plugins) if (p.fillSlots) out = await p.fillSlots(out);
	return out;
}
